services:
  postgres:
    image: postgres:16
    container_name: optimax-db
    environment:
      POSTGRES_DB: optimaxdb
      POSTGRES_USER: optimax
      POSTGRES_PASSWORD: optimax
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: